Use StarbucksDB;

-- view all customers
SELECT * FROM customer;

-- view all outlets
SELECT * FROM outlet;

-- view all menu items with their category 
SELECT m.item_name, c.category_name, m.price
FROM menu_item m
JOIN category c ON m.category_id = c.category_id;

-- view orders with customer names
SELECT o.order_id, c.customer_name, o.order_date, o.total_amount
FROM orders o
JOIN customer c ON o.customer_id = c.customer_id;

-- view total orders placed at each outlet
SELECT outlet_id, COUNT(order_id) AS total_orders
FROM orders
GROUP BY outlet_id;

-- view total revenue generated by each outlet
SELECT outlet_id, SUM(total_amount) AS total_revenue
FROM orders
GROUP BY outlet_id;

-- view loyalty customers
SELECT customer_name, email
FROM customer
WHERE loyalty_member = 1;

-- view items ordered in each order
SELECT oi.order_id, m.item_name, oi.quantity
FROM order_item oi
JOIN menu_item m ON oi.item_id = m.item_id;

-- view payment details for orders 
SELECT o.order_id, p.payment_mode, p.payment_status
FROM orders o
JOIN payment p ON o.order_id = p.order_id;

-- view staff working at each outlet
SELECT s.staff_name, s.staff_role, o.outlet_name
FROM staff s
JOIN outlet o ON s.outlet_id = o.outlet_id;

